import type { DeepWiden } from "./ru";
import { ru } from "./ru";

export const en = {
  nav: { design: "Design", inside: "Inside", switches: "Switches", connectivity: "Connectivity", configurator: "Configurator", specs: "Specifications", menu: "Open menu" },
  hero: { eyebrow: "75% mechanical keyboard", title: "FORM 75", subtitle: "Precision in every press.", support: "CNC aluminium. Gasket-mounted. Three seamless ways to connect.", price: "From $249", cta: "Explore", hint: "Scroll to take it apart" },
  story: {
    designKicker: "01 — Form", designTitle: "Cut from solid aluminium.", designCopy: "A precisely CNC-machined 6063 aluminium enclosure. Soft bevels catch the light while its monolithic mass absorbs unwanted vibration.",
    explodedKicker: "02 — Architecture", explodedTitle: "Reduced to the idea.", explodedCopy: "Every layer has one job. Nothing is accidental — from the bottom case to the key profile.",
    insideKicker: "03 — Inside", insideTitle: "Quiet inside. Precise outside.", insideCopy: "A gasket mount isolates the plate from the case. Two damping layers control resonance, while the hot-swap PCB lets you change switches without soldering.",
    switchKicker: "04 — Switches", switchTitle: "Character at your fingertips.", switchCopy: "Three mechanisms, one considered enclosure. Press the switch and choose your feel.",
    reassemblyKicker: "05 — Whole", reassemblyTitle: "Built around your rhythm.", reassemblyCopy: "The layers return to place. The construction fades from attention — only the action remains.",
    layers: ["Keycaps", "Switches", "Plate", "Dampening", "PCB", "Battery", "Bottom case"], press: "Press the switch",
    linear: { name: "FORM Linear", force: "45 gf", feel: "Smooth" }, tactile: { name: "FORM Tactile", force: "55 gf", feel: "Defined tactile bump" }, silent: { name: "FORM Silent", force: "45 gf", feel: "Dampened" }, actuation: "2.0 mm actuation",
  },
  wireless: { kicker: "Connectivity", title: "Three ways to connect. Zero compromise.", copy: "Move between devices without breaking your flow. FORM 75 remembers multiple Bluetooth connections and runs for up to 120 hours with lighting off.", wired: "USB‑C", wiredMeta: "1000 Hz · power and data", radio: "2.4 GHz", radioMeta: "1000 Hz · minimal latency", bluetooth: "Bluetooth", bluetoothMeta: "Multiple devices", battery: "4500 mAh", hours: "up to 120 hours", compatibility: "Windows / macOS" },
  config: { kicker: "Configurator", title: "Build your FORM.", copy: "Case, keycaps, switch feel and light — every change appears on your keyboard in real time.", finish: "Case", keycaps: "Keycaps", switches: "Switches", backlight: "Backlight", backlightOn: "On", backlightOff: "Off", lightColor: "Light colour", graphite: "Graphite", silver: "Silver", sand: "Sand", obsidian: "Obsidian", porcelain: "Porcelain", ember: "Ember", linear: "FORM Linear", tactile: "FORM Tactile", silent: "FORM Silent", neutral: "Neutral", warm: "Warm", ice: "Cool", cta: "Configure — $249", concept: "Interactive configuration · no checkout", rotate: "Rotate with your mouse or finger" },
  specs: { kicker: "Details", title: "Designed as a whole.", items: [["Layout", "75%"], ["Case", "CNC-machined 6063 aluminium"], ["Mount", "Gasket mount"], ["PCB", "Hot-swap, 5-pin MX"], ["Lighting", "South-facing per-key RGB"], ["Keycaps", "Double-shot PBT"], ["Connectivity", "USB-C / Bluetooth / 2.4 GHz"], ["Battery", "4500 mAh"], ["Polling", "Up to 1000 Hz"], ["Compatibility", "Windows / macOS"], ["NKRO", "Yes"], ["Weight", "Approximately 1.7 kg"], ["Rotary knob", "CNC aluminium"], ["Price", "$249"]] },
  final: { eyebrow: "FORM 75", title: "The tool that disappears between thought and action.", cta: "Create your FORM", disclaimer: "FORM 75 is a fictional concept product." },
  assistant: { trigger: "ASK FORM", open: "Open FORM AI", title: "FORM AI", subtitle: "Your guide to FORM 75 and mechanical keyboards", close: "Close assistant", clear: "Clear conversation", welcome: "Ask about FORM 75 construction, connectivity, or choosing switches.", placeholder: "Ask about FORM 75…", send: "Send", loading: "FORM AI is thinking…", unavailable: "FORM AI is not available in this environment yet.", genericError: "We could not get an answer. Please try again.", prompts: ["Which switch should I choose?", "Is FORM 75 suitable for gaming?", "Does it have Bluetooth?", "How are Linear and Tactile different?"] },
  a11y: { theme: "Toggle theme", language: "Change language", scene: "Interactive three-dimensional model of the FORM 75 keyboard", webglFallback: "A static model is shown because WebGL2 is unavailable. The configurator and site content remain usable." },
} satisfies DeepWiden<typeof ru>;
